export const GET_CHAIR_REQUEST = "GET_CHAIR_REQUEST";
export const GET_CHAIR_SUCCESS = "GET_CHAIR_SUCCESS";
export const GET_CHAIR_FAILED = "GET_CHAIR_FAILED";
//Đặt vé
export const BOOK_TICKET = "BOOK_TICKET";

export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST";
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_REQUEST";
export const BOOK_TICKET_FAILED = "BOOK_TICKET_FAILED";

export const RESET_BOOKING_CHAIR = "RESET_BOOKING_CHAIR";
export const STOP_TIME_BOOKING = "STOP_TIME_BOOKING";